### ISSUE TITLE
🐛 [BUG] - Adding discount code fails in checkout step

### ISSUE THREAD

**Issue by Shoprunners** [Oksydan/modern-prestashop-starter-theme#411] opened 2024-06-03 11:43 UTC
### Description

When you have personalized / no code  voucher codes which appear beneath the cart summary, you can click on them and they will be added to the cart and the summary reloads. Works great. If you want to do the same in the last step "do you have a voucher code". and klick on the code, it will be pasted in the input field and in the background, also added to your cart calculations. But the page / area is not refreshed. Reloading whole page, shows the code / discount.

Why?

The theme uses a minimized header in this step and no is_shopping_cart module is loaded. This module is responsible for reloading the cart. Workaround is, to use the normal header during checkout process and adapt the tpl file. 
Don't have a better solution for now. 

### Node.js version

1410

### php version

v8.1

### OS and it's version

Linux

### Browsers

Chrome

### Required module/theme

3

### Reproduction steps

```bash
1. Create a voucher  without code -> visible in the cart and addable via click
2. Add the voucher in "Show cart" step. should work
3. Remove it again
4. Go to next step and do the same. -> not working as expected. A explicit click on "add voucher to cart" will give you the message, "already in cart".
```

**Comment by Oksydan** [comment] 2024-06-08 21:03
Hi @Shoprunners,

is_shoppingcart module isn't responsible for reloading the cart at all. 
I wasn't able to reproduce this issue on develop branch. 
Please let me know the exact version of the Falcon theme you are using.

**Comment by Oksydan** [comment] 2024-08-19 16:39
Hi @Shoprunners,

since we had not news from you in over 2 months, I am closing this issue. Feel free to reopen this issue or create a new one.

**Closed as completed by Oksydan** 2024-08-19 16:39 UTC
Labels: bug, waiting for author
