### ISSUE TITLE
Problem with increase quantity in product page

### ISSUE THREAD

**Issue by damiantymkowski** [Oksydan/modern-prestashop-starter-theme#71] opened 2022-02-03 09:05 UTC
PrestaShop version: 1.7.8.2
starter theme 2.0.2
is_themecore-1.1.2

When I try to increase quantity or change combination of the product, form HTML disappear. 

Before:
![image](https://user-images.githubusercontent.com/41170239/152312007-e2a38cce-eeb5-4bab-9649-33d6806a8785.png)

After:
![image](https://user-images.githubusercontent.com/41170239/152312055-745a149e-6c7b-4cf0-b411-e9f7b65d5096.png)

_product.tpl_
```
   <div class="product-information ">
            {block name='product_description_short'}
              <div id="product-description-short-{$product.id}" class="product-description cms-content">{$product.description_short nofilter}</div>
            {/block}

            {block name='product_prices'}
              {include file='catalog/_partials/product-prices.tpl'}
            {/block}
            {if $product.is_customizable && count($product.customizations.fields)}
              {block name='product_customization'}
                {include file="catalog/_partials/product-customization.tpl" customizations=$product.customizations}
              {/block}
            {/if}

            <div class="product-actions js-product-actions mt-3 col-xl-6 p-0">
              {block name='product_buy'}
                <form action="{$urls.pages.cart}" method="post" id="add-to-cart-or-refresh">
                  <input type="hidden" name="token" value="{$static_token}">
                  <input type="hidden" name="id_product" value="{$product.id}" id="product_page_product_id">
                  <input type="hidden" name="id_customization" value="{$product.id_customization}" id="product_customization_id" class="js-product-customization-id">

                  {block name='product_variants'} 
                    {include file='catalog/_partials/product-variants.tpl'}
                  {/block}

                  {block name='product_pack'}
                    {if $packItems}
                      <section class="product-pack">
                        <p class="h4">{l s='This pack contains' d='Shop.Theme.Catalog'}</p>
                        <div class="card-group-vertical mb-4">
                          {foreach from=$packItems item="product_pack"}
                            {block name='product_miniature'}
                              {include file='catalog/_partials/miniatures/pack-product.tpl' product=$product_pack showPackProductsPrice=$product.show_price}
                            {/block}
                          {/foreach}
                        </div>
                    </section>
                    {/if}
                  {/block}

                  {block name='product_discounts'}
                    {include file='catalog/_partials/product-discounts.tpl'}
                  {/block}

                  {block name='product_add_to_cart'}
                    {include file='catalog/_partials/product-add-to-cart.tpl'}
                  {/block}
                  <section class="additional-info d-flex flex-column ml-2 mt-3">
                  {if $product.reference}
                    <div class="row"><span class="mr-1">Number: </span> {$product.reference}</div>
                  {/if}
                      <section class="">
                          <dl class="row no-gutters mb-0 ml-n2 mt-2">
                              {foreach from=$product.grouped_features item=feature}
                                  <dt class="col-3  {if !$feature@last}  {/if}">{$feature.name}:</dt>
                                  <dd class="col-7 {if !$feature@last}{/if}">{$feature.value|escape:'htmlall'|nl2br nofilter}</dd>
                              {/foreach}
                          </dl>
                      </section>
                  {if $product.quantity > 0}
                   <div class="row mt-1"> <span class="mr-1">Status: </span><span style="color: #03894A; font-weight: 600;">available</span></div>
                  {/if}
                    {if $product.delivery_in_stock}
                      <div class="row mt-1"><span class="mr-1">Estimated delivery time: </span><span class="font-weight-bold"></span></div>
                    {/if}
                    <div class="row mt-1"><span class="mr-1">Delivery price: </span><span class="font-weight-bold"> price </span><a class="ml-1" href="">look more</a></div>

                  </section>

                  {block name='product_additional_info'}
                    {include file='catalog/_partials/product-additional-info.tpl'}
                  {/block}

                  {* Input to refresh product HTML removed, block kept for compatibility with themes *}
                  {block name='product_refresh'}{/block}
                </form>
              {/block}
            </div>
          </div>

```

**Comment by Oksydan** [comment] 2022-02-03 20:42
HI @damiantymkowski,
I am not able to reproduce problem.
That part of `product.tpl` provided by you didn't help me reproduce it either. 
There is probably error somewhere inside your code (might be javascript related).

**Comment by damiantymkowski** [comment] 2022-02-04 23:37
Thanks for the reply.
It was a problem with the unclosed tag "div" - `js-product-prices` in the `product-prices.tpl`

**Comment by Oksydan** [comment] 2022-02-07 08:04
It is good to hear that you solved your problem.
I am closing this issue. If your find any problem please create another issue.

**Closed by Oksydan** 2022-02-07 08:04 UTC
