### ISSUE TITLE
Compile problem - bad value / no value sass

### ISSUE THREAD

**Issue by slawekmoskal** [Oksydan/modern-prestashop-starter-theme#69] opened 2022-01-30 02:20 UTC
File _nice_select.scss line: 5 
`$input-height: $custom-select-height;`

After run build I have error message:

throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Undefined operation \"-calc(1.5em + 1rem + 2px)\".\n   ╷\n93 │         transform: scale(0.75) translateY(-$input-height / 2);\n   │                                           ^^^^^^^^^^^^^^\n   ╵\n  css/theme/vendors/_nice-select.scss 93:37  @import\n  css/theme/vendors/_index.scss 1:9          @import\n  css/theme/_index.scss 2:9   @import\n  css/theme.scss 2:9  root stylesheet");

Any change $input-height (ex. 14px) - build works fine.

**Comment by Oksydan** [comment] 2022-02-03 20:47
Hi @slawekmoskal.
I need some information about your environment configuration since I am not able to reproduce the problem.
What I need:
 - your system with version,
 - `node` version (run in terminal `node -v`),
 - did you make any changes to package.json (upgraded any dependencies, provide me package.json file)?

**Comment by slawekmoskal** [comment] 2022-02-03 20:54
Hi.
MacOS 12.1, CPU M1

VSC version: 1.63.2 (Universal)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

package.json was not changed.

Nów my any project have custom setting like:

```
	"liveSassCompile.settings.includeItems": [
		"/public_html/public/default/scss/style.scss",
	],
```

**Comment by Oksydan** [comment] 2022-03-14 21:36
Hi @slawekmoskal,
unfortunately I am not able to reproduce an issue 😕 with macOs and the same node version.
I am closing this issue for now. It might be environment related issue but w/o reproducing problem I am not able to fix it.
Feel free to reopen or create another issue if you are able to provide more information how to reproduce the problem.

**Closed by Oksydan** 2022-03-14 21:36 UTC
