### ISSUE TITLE
Cart Summary does not updated when changes quantity on Cart details

### ISSUE THREAD

**Issue by caovillanueva** [Oksydan/modern-prestashop-starter-theme#44] opened 2021-09-21 13:20 UTC
Add some items to cart.
Go to cart page.
In cart page when you update quantities in products the price is updated only in each item row. But the subtotal and total price not changes values via ajax. you need to refresh the page to see the current values.

I have the debug mode activated but not show errors.

**Comment by Oksydan** [comment] 2021-09-21 18:12
Hi.
I am not able to reproduce problem.
Can you provide me more information:
- prestashop version,
- php version,
- theme version.

**Comment by caovillanueva** [comment] 2021-09-28 17:31
Sure:
Prestashop 1.7.7.4
Server information Linux #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64
Server software version: LiteSpeed
PHP version: 7.1.33
Memory limit: 1024M
PrestaShop version: 1.7.7.4
Theme: modern-prestashop-starter-theme Version 1.0.3
I had to put a custom jquery to solve the problem for while. in theme.js:


`prestashop.on(
  'updateCart',
  function (event) {   
    var patch_Subtotal = event.resp.cart.totals.total.value;
    var patch_totalTaxExcl = event.resp.cart.totals.total_excluding_tax.value;
    $('#cart-subtotal-products > span.value').text(patch_Subtotal);
    $('#cart div.cart-grid-right.col-12.col-lg-4 > div > div:nth-child(2) > div:nth-child(3) > span.value').text(patch_totalTaxExcl);
  }
);`

**Comment by Oksydan** [comment] 2021-09-28 18:50
It is very old version of starter. Problem has been fixed in version 1.1.2. Link to commit with fixed file: https://github.com/Oksydan/modern-prestashop-starter-theme/commit/1d66749916eea390f018fc19563a7bdfb9925a48

**Closed** 2021-10-06 12:00 UTC
